api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        force_eager: false
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
